--CREATING TABLEs--

CREATE TABLE USER_TB(
	USERID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(150) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL UNIQUE,
	PASSWORD NVARCHAR(100) NOT NULL,
	REGISTRATIONDATE DATETIME NOT NULL,
	BIRTHDATE DATETIME NOT NULL
	PRIMARY KEY(USERID))
GO

CREATE TABLE AUCTION_TB(
	AUCTIONID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(150) NOT NULL,
	STARTDATE DATE NOT NULL,
	STARTHOUR TIME(7) NOT NULL,
	FINISHTDATE DATE NOT NULL,
	FINISHOUR TIME(7) NOT NULL,
	DESCRIPTION NVARCHAR(100) NOT NULL,
	VALUE INTEGER NOT NULL,
	USERID UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY(AUCTIONID),
	FOREIGN KEY(USERID)
		REFERENCES USER_TB(USERID))
GO


	--CONSULTING TABLES--

SELECT * FROM USER_TB

GO

SELECT * FROM AUCTION_TB

GO
